name: simple_book_explorer
description: "A simple book explorer application built with Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
