name: simple_book_explorer
description: "A simple book explorer application built with Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dynamic_height_page_view: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  lottie: ^3.3.2
  palette_generator_master: ^1.0.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/appicon/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

flutter_gen:
  output: lib/gen/
  line_length: 80

  assets:
    enabled: true

  fonts:
    enabled: true

  integrations:
    flutter_svg: true
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon/book_icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/appicon/book_icon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/appicon/book_icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/appicon/book_icon.jpg"
